version: '3.8'

services:
  backend-1:
    image: arthurandrade1/rinhabackend
    container_name: back1
    ports:
      - "8080"
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379,abortConnect=false
    networks:
      - backend
      - payment-processor

  backend-2:
    image: arthurandrade1/rinhabackend
    container_name: back2
    ports:
      - "8080"
    depends_on:
      - redis
    environment:
      - Redis__ConnectionString=redis:6379
    networks:
      - backend
      - payment-processor

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  payment-processor:
    name: payment-processor
    driver: bridge
    external: true                